##서버 포트 설정
#server.port=8080 
#
##인코딩 UTF-8 설정
#server.servlet.encoding.charset=UTF-8
#server.servlet.encoding.enabled=true
#server.servlet.encoding.force=true
#server.servlet.encoding.force-request=true
#server.servlet.encoding.force-response=true
#server.tomcat.uri-encoding=UTF-8
#
#
##뷰리졸버 설정
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springboot_seongjun?useUnicode=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: toor
  security:
    user:
      name: test
      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: 86907553045-q3h0iti3rcd6953tepqpquekurevu5n2.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          naver:
            client-id: 952Kk6ulqxNVlqStNwdN
            client-secret: 69hbCXNZ7f
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          
    
mybatis:
  mapper-locations:
  - /mappers/*.xml
  
  
file:
  path: C:/seongjun/springboot_workspace/springboot-study-20220510/upload/